#!/usr/bin/env python3
"""The square of each exercise animation that its small thumbnail shows.

    python3 tools/lottie/thumb_crops.py [--chrome PATH]

The animations are drawn on a 400 x 400 canvas with the figure in the lower
part, so a 44 px thumbnail of the whole canvas shows a tiny Goro. This renders
every assets/animations/*.json with lottie-web in headless Chrome (12 frames
each), takes the box of what is drawn over all of them (rows painted across
more than 70 % of the width - a floor or a background - are left out), makes
it a square with some air round it and writes the squares to
lib/data/static/animation_crops.dart for ExerciseThumb. Run it again after
adding or redrawing an animation (a test fails while a file has no square).
"""

import argparse
import json
import pathlib
import re
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
ANIM = ROOT / 'assets' / 'animations'
OUT = ROOT / 'lib' / 'data' / 'static' / 'animation_crops.dart'
CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

PAGE = '''<html><body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.12.2/lottie.min.js"></script>
<pre id="out"></pre>
<script>
const DATA = %s;
const res = {};
for (const [name, anim] of Object.entries(DATA)) {
  const div = document.createElement('div');
  div.style.cssText = 'width:200px;height:200px;position:absolute;left:-9999px';
  document.body.appendChild(div);
  const a = lottie.loadAnimation({container: div, renderer: 'canvas', loop: false,
      autoplay: false, animationData: anim});
  let x0 = 1e9, y0 = 1e9, x1 = -1, y1 = -1;
  for (let k = 0; k < 12; k++) {
    a.goToAndStop(Math.floor(k * a.totalFrames / 12), true);
    const c = div.querySelector('canvas');
    const w = c.width, h = c.height, s = 400 / w;
    const px = c.getContext('2d').getImageData(0, 0, w, h).data;
    for (let y = 0; y < h; y++) {
      let n = 0, rx0 = w, rx1 = -1;
      for (let x = 0; x < w; x++) {
        if (px[(y * w + x) * 4 + 3] > 40) { n++; rx0 = Math.min(rx0, x); rx1 = Math.max(rx1, x); }
      }
      if (n === 0 || n > 0.7 * w) continue;
      x0 = Math.min(x0, rx0 * s); x1 = Math.max(x1, (rx1 + 1) * s);
      y0 = Math.min(y0, y * s); y1 = Math.max(y1, (y + 1) * s);
    }
  }
  res[name] = [x0, y0, x1, y1].map(Math.round);
  a.destroy(); div.remove();
}
document.getElementById('out').textContent = 'BOXES' + JSON.stringify(res) + 'END';
</script></body></html>'''

PAD = 0.12          # air round the figure, of the box side
MIN_SIDE = 180      # a small figure is not blown up past this
CANVAS = 400


def square(box):
    """The square centred on the figure. It may reach past the canvas (the
    thumbnail's tile shows there): a wide figure lying on the floor stays in
    the middle of its tile instead of at its bottom."""
    x0, y0, x1, y1 = box
    side = max(x1 - x0, y1 - y0)
    side = max(MIN_SIDE, round(side * (1 + 2 * PAD)))
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    return round(cx - side / 2), round(cy - side / 2), side


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--chrome', default=CHROME)
    args = ap.parse_args()
    data = {p.stem: json.loads(p.read_text()) for p in sorted(ANIM.glob('*.json'))}
    with tempfile.TemporaryDirectory() as tmp:
        page = pathlib.Path(tmp) / 'boxes.html'
        page.write_text(PAGE % json.dumps(data))
        dom = subprocess.run(
            [args.chrome, '--headless=new', '--disable-gpu', '--virtual-time-budget=60000',
             '--dump-dom', page.as_uri()],
            capture_output=True, text=True, check=True).stdout
    boxes = json.loads(re.search(r'BOXES(.*)END', dom).group(1))
    assert set(boxes) == set(data), 'every animation was measured'
    lines = [
        '// GENERATED by tools/lottie/thumb_crops.py - do not edit by hand.',
        '',
        '/// The square of each exercise animation (on its 400 x 400 canvas) that',
        '/// [ExerciseThumb] shows: the figure over all its frames with some air',
        '/// round it, as (left, top, side); it may reach past the canvas.',
        'const Map<String, (int, int, int)> kAnimationCrops = {',
    ]
    for name in sorted(boxes):
        left, top, side = square(boxes[name])
        lines.append(f"  'assets/animations/{name}.json': ({left}, {top}, {side}),")
    lines += ['};', '']
    OUT.write_text('\n'.join(lines))
    print(f'{OUT.relative_to(ROOT)}: {len(boxes)} squares')


if __name__ == '__main__':
    main()
