"""The course hosts: Luna the owl (Evening Stretch) and Raffi the giraffe
(Healthy Body), drawn in Goro's flat style (rounded tile, soft glow, no
outlines, big eyes with highlights, the light-blue accent of Goro's headband).

    python3 tools/characters/gen_hosts.py [OUT_DIR]

Writes ``luna_portrait.svg`` / ``luna_cheer.svg`` and ``raffi_portrait.svg`` /
``raffi_cheer.svg`` into OUT_DIR (default: assets/hosts). The portrait sits on
the course cards (40-48 px), the cheer pose on the workout summary (120 px).
Edit this script, not the SVG files.
"""
import sys
from pathlib import Path

ACCENT = '#A8D8FF'          # Goro's headband
ACCENT_D = '#7FBFF5'
WHITE = '#FFFFFF'
PUPIL = '#1E1C36'


def tile(grad_id, top, bottom, glow):
    return f'''<defs>
    <linearGradient id="{grad_id}" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:{top}"/>
      <stop offset="100%" style="stop-color:{bottom}"/>
    </linearGradient>
    <radialGradient id="{grad_id}Glow" cx="50%" cy="48%" r="46%">
      <stop offset="0%" style="stop-color:{glow};stop-opacity:0.28"/>
      <stop offset="100%" style="stop-color:{glow};stop-opacity:0"/>
    </radialGradient>
  </defs>
  <rect width="1024" height="1024" rx="224" fill="url(#{grad_id})"/>
  <circle cx="512" cy="500" r="430" fill="url(#{grad_id}Glow)"/>'''


def svg(title, body):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">\n'
            f'  <!-- {title}. Generated by tools/characters/gen_hosts.py: edit the script, not this file. -->\n'
            f'  {body}\n</svg>\n')


def eye(cx, cy, r, look=(0, 0), lid=0.0, lid_color='#000', closed=False, closed_color=PUPIL):
    """A round eye; ``lid`` (0..1) lowers an upper lid of ``lid_color``;
    ``closed`` draws a happy closed eye (an arc) instead."""
    if closed:
        return (f'<path d="M{cx - r * 0.8:.0f} {cy + r * 0.1:.0f} Q{cx:.0f} {cy - r * 0.75:.0f} '
                f'{cx + r * 0.8:.0f} {cy + r * 0.1:.0f}" stroke="{closed_color}" stroke-width="{r * 0.22:.0f}" '
                f'stroke-linecap="round" fill="none"/>')
    px, py = cx + look[0], cy + look[1]
    out = (f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{WHITE}"/>'
           f'<circle cx="{px}" cy="{py}" r="{r * 0.55:.0f}" fill="{PUPIL}"/>'
           f'<circle cx="{px + r * 0.22:.0f}" cy="{py - r * 0.24:.0f}" r="{r * 0.17:.0f}" fill="{WHITE}"/>')
    if lid > 0:
        # a relaxed lid: its edge sags in the middle (a flat edge looks bored)
        y = cy - r + 2 * r * lid
        out += (f'<path d="M{cx - r - 2} {cy - r - 4} L{cx + r + 2} {cy - r - 4} L{cx + r + 2} {y - r * 0.3:.0f} '
                f'Q{cx} {y + r * 0.45:.0f} {cx - r - 2} {y - r * 0.3:.0f} Z" fill="{lid_color}"/>')
    return out


# ══ Luna, the owl ════════════════════════════════════════════════════════════

L_BODY = '#6E6AAE'      # feathers
L_DARK = '#545090'      # wings, tufts
L_BELLY = '#D8D1F2'
L_MARK = '#B7ADE2'
L_DISC = '#EBE6FA'      # facial disc
L_BEAK = '#F2B544'
L_FEET = '#E9A13B'


def night_sky():
    stars = [(190, 230, 10), (262, 160, 6), (800, 300, 7), (868, 420, 5), (150, 420, 6),
             (330, 260, 4), (720, 180, 5), (880, 640, 6), (140, 700, 5)]
    out = [tile('lunaBg', '#3D428F', '#1D2052', '#8F95E8')]
    out.append('<path d="M780 110 A110 110 0 1 0 880 260 A86 86 0 1 1 780 110 Z" fill="#FFE9A8"/>')
    for x, y, r in stars:
        out.append(f'<circle cx="{x}" cy="{y}" r="{r}" fill="#FFF6D6" opacity="0.85"/>')
    return '\n  '.join(out)


def luna_head(cx, cy, s=1.0, eyes='calm'):
    """Head of the owl centred at (cx, cy); ``eyes`` calm | happy."""
    def p(x, y):
        return f'{cx + x * s:.0f} {cy + y * s:.0f}'
    parts = [
        # ear tufts
        f'<path d="M{p(-150, -150)} L{p(-205, -290)} L{p(-70, -205)} Z" fill="{L_DARK}"/>',
        f'<path d="M{p(150, -150)} L{p(205, -290)} L{p(70, -205)} Z" fill="{L_DARK}"/>',
        # head
        f'<ellipse cx="{cx}" cy="{cy}" rx="{235 * s:.0f}" ry="{215 * s:.0f}" fill="{L_BODY}"/>',
        # facial disc: two rounded lobes
        f'<ellipse cx="{cx - 88 * s:.0f}" cy="{cy + 6 * s:.0f}" rx="{108 * s:.0f}" ry="{118 * s:.0f}" fill="{L_DISC}"/>',
        f'<ellipse cx="{cx + 88 * s:.0f}" cy="{cy + 6 * s:.0f}" rx="{108 * s:.0f}" ry="{118 * s:.0f}" fill="{L_DISC}"/>',
        f'<path d="M{p(-60, -112)} Q{p(0, -60)} {p(60, -112)} L{p(0, -30)} Z" fill="{L_BODY}"/>',
    ]
    if eyes == 'happy':
        parts.append(eye(cx - 88 * s, cy + 4 * s, 62 * s, closed=True, closed_color=L_DARK))
        parts.append(eye(cx + 88 * s, cy + 4 * s, 62 * s, closed=True, closed_color=L_DARK))
    else:
        parts.append(eye(cx - 88 * s, cy + 6 * s, 62 * s, look=(6 * s, 6 * s)))
        parts.append(eye(cx + 88 * s, cy + 6 * s, 62 * s, look=(-6 * s, 6 * s)))
    # beak and blush
    parts += [
        f'<path d="M{p(-26, 70)} L{p(26, 70)} L{p(0, 122)} Z" fill="{L_BEAK}"/>',
        f'<ellipse cx="{cx - 150 * s:.0f}" cy="{cy + 96 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="#F5A8C8" opacity="0.45"/>',
        f'<ellipse cx="{cx + 150 * s:.0f}" cy="{cy + 96 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="#F5A8C8" opacity="0.45"/>',
    ]
    return '\n  '.join(parts)


def luna_body(cx, top, s=1.0, wing='down'):
    """Body below the head: egg shape, belly with V-marks, folded wings
    (``wing`` down | up: the right wing raised in a stretch), a scarf."""
    h = 380 * s
    w = 250 * s
    parts = [
        f'<ellipse cx="{cx}" cy="{top + h * 0.5:.0f}" rx="{w:.0f}" ry="{h * 0.56:.0f}" fill="{L_BODY}"/>',
        f'<ellipse cx="{cx}" cy="{top + h * 0.58:.0f}" rx="{w * 0.66:.0f}" ry="{h * 0.44:.0f}" fill="{L_BELLY}"/>',
    ]
    for row in range(3):
        y = top + h * (0.36 + row * 0.17)
        for col in range(-2 + row % 2, 3, 2):
            x = cx + col * 44 * s
            if abs(col) * 44 * s > w * 0.5:
                continue
            parts.append(f'<path d="M{x - 16 * s:.0f} {y:.0f} L{x:.0f} {y + 16 * s:.0f} L{x + 16 * s:.0f} {y:.0f}" '
                         f'stroke="{L_MARK}" stroke-width="{8 * s:.0f}" stroke-linecap="round" stroke-linejoin="round" fill="none"/>')
    # left wing, folded
    parts.append(f'<path d="M{cx - w * 0.82:.0f} {top + h * 0.22:.0f} Q{cx - w * 1.18:.0f} {top + h * 0.62:.0f} '
                 f'{cx - w * 0.74:.0f} {top + h * 0.98:.0f} Q{cx - w * 0.56:.0f} {top + h * 0.6:.0f} '
                 f'{cx - w * 0.82:.0f} {top + h * 0.22:.0f} Z" fill="{L_DARK}"/>')
    if wing == 'up':
        # right wing stretched up and out
        parts.append(f'<path d="M{cx + w * 0.7:.0f} {top + h * 0.3:.0f} Q{cx + w * 1.5:.0f} {top - h * 0.2:.0f} '
                     f'{cx + w * 1.32:.0f} {top - h * 0.58:.0f} Q{cx + w * 1.12:.0f} {top - h * 0.1:.0f} '
                     f'{cx + w * 0.62:.0f} {top + h * 0.12:.0f} Z" fill="{L_DARK}"/>')
        for i in range(3):
            fx = cx + w * (1.3 - i * 0.1)
            fy = top - h * (0.52 - i * 0.1)
            parts.append(f'<ellipse cx="{fx:.0f}" cy="{fy:.0f}" rx="{22 * s:.0f}" ry="{40 * s:.0f}" '
                         f'fill="{L_DARK}" transform="rotate({-30 + i * 12} {fx:.0f} {fy:.0f})"/>')
    else:
        parts.append(f'<path d="M{cx + w * 0.82:.0f} {top + h * 0.22:.0f} Q{cx + w * 1.18:.0f} {top + h * 0.62:.0f} '
                     f'{cx + w * 0.74:.0f} {top + h * 0.98:.0f} Q{cx + w * 0.56:.0f} {top + h * 0.6:.0f} '
                     f'{cx + w * 0.82:.0f} {top + h * 0.22:.0f} Z" fill="{L_DARK}"/>')
    # scarf in Goro's headband blue
    parts.append(f'<path d="M{cx - w * 0.78:.0f} {top + h * 0.08:.0f} Q{cx:.0f} {top + h * 0.22:.0f} '
                 f'{cx + w * 0.78:.0f} {top + h * 0.08:.0f} L{cx + w * 0.74:.0f} {top + h * 0.2:.0f} '
                 f'Q{cx:.0f} {top + h * 0.34:.0f} {cx - w * 0.74:.0f} {top + h * 0.2:.0f} Z" fill="{ACCENT}"/>')
    parts.append(f'<path d="M{cx + w * 0.34:.0f} {top + h * 0.22:.0f} L{cx + w * 0.52:.0f} {top + h * 0.52:.0f} '
                 f'L{cx + w * 0.3:.0f} {top + h * 0.5:.0f} Z" fill="{ACCENT_D}"/>')
    return '\n  '.join(parts)


def luna_feet(cx, y, s=1.0):
    out = []
    for dx in (-70, 70):
        for t in (-22, 0, 22):
            out.append(f'<ellipse cx="{cx + (dx + t) * s:.0f}" cy="{y:.0f}" rx="{13 * s:.0f}" ry="{26 * s:.0f}" fill="{L_FEET}"/>')
    return '\n  '.join(out)


def luna_portrait():
    body = [night_sky(), luna_body(512, 690, 1.05), luna_head(512, 520, 1.0, 'calm')]
    return svg('LUNA — portrait (Evening Stretch host, the owl)', '\n  '.join(body))


def luna_cheer():
    body = [night_sky(),
            '<rect x="120" y="880" width="784" height="34" rx="17" fill="#2A2D66"/>',
            luna_feet(512, 872, 0.9),
            luna_body(512, 520, 0.9, wing='up'),
            luna_head(512, 380, 0.82, 'happy')]
    return svg('LUNA — cheer (stretching a wing, eyes closed happily)', '\n  '.join(body))


# ══ Raffi, the giraffe ═══════════════════════════════════════════════════════

R_COAT = '#F2C462'
R_SPOT = '#C9782F'
R_MUZZLE = '#FBE6B8'
R_EAR_IN = '#E3A04A'
R_HORN = '#E2A452'
R_HORN_TIP = '#6E4321'
R_MANE = '#B8642A'
R_HOOF = '#5A3A22'


def green_tile():
    return tile('raffiBg', '#5DC28C', '#2B8556', '#C8F5D8')


def raffi_head(cx, cy, s=1.0, tilt=0.0, eyes='open'):
    def p(x, y):
        return f'{cx + x * s:.0f} {cy + y * s:.0f}'
    parts = [f'<g transform="rotate({tilt} {cx} {cy})">',
             # ossicones
             f'<rect x="{cx - 92 * s:.0f}" y="{cy - 270 * s:.0f}" width="{34 * s:.0f}" height="{120 * s:.0f}" rx="{16 * s:.0f}" fill="{R_HORN}"/>',
             f'<rect x="{cx + 58 * s:.0f}" y="{cy - 270 * s:.0f}" width="{34 * s:.0f}" height="{120 * s:.0f}" rx="{16 * s:.0f}" fill="{R_HORN}"/>',
             f'<circle cx="{cx - 75 * s:.0f}" cy="{cy - 272 * s:.0f}" r="{30 * s:.0f}" fill="{R_HORN_TIP}"/>',
             f'<circle cx="{cx + 75 * s:.0f}" cy="{cy - 272 * s:.0f}" r="{30 * s:.0f}" fill="{R_HORN_TIP}"/>',
             # ears, sideways
             f'<ellipse cx="{cx - 200 * s:.0f}" cy="{cy - 130 * s:.0f}" rx="{84 * s:.0f}" ry="{34 * s:.0f}" fill="{R_COAT}" transform="rotate(-24 {cx - 200 * s:.0f} {cy - 130 * s:.0f})"/>',
             f'<ellipse cx="{cx - 196 * s:.0f}" cy="{cy - 128 * s:.0f}" rx="{56 * s:.0f}" ry="{18 * s:.0f}" fill="{R_EAR_IN}" transform="rotate(-24 {cx - 196 * s:.0f} {cy - 128 * s:.0f})"/>',
             f'<ellipse cx="{cx + 200 * s:.0f}" cy="{cy - 130 * s:.0f}" rx="{84 * s:.0f}" ry="{34 * s:.0f}" fill="{R_COAT}" transform="rotate(24 {cx + 200 * s:.0f} {cy - 130 * s:.0f})"/>',
             f'<ellipse cx="{cx + 196 * s:.0f}" cy="{cy - 128 * s:.0f}" rx="{56 * s:.0f}" ry="{18 * s:.0f}" fill="{R_EAR_IN}" transform="rotate(24 {cx + 196 * s:.0f} {cy - 128 * s:.0f})"/>',
             # head: long oval, wider at the top
             f'<path d="M{p(-150, -110)} C{p(-160, -230)} {p(160, -230)} {p(150, -110)} '
             f'C{p(160, 20)} {p(140, 150)} {p(110, 200)} L{p(-110, 200)} C{p(-140, 150)} {p(-160, 20)} {p(-150, -110)} Z" fill="{R_COAT}"/>',
             # forehead spots
             f'<ellipse cx="{cx - 40 * s:.0f}" cy="{cy - 150 * s:.0f}" rx="{30 * s:.0f}" ry="{20 * s:.0f}" fill="{R_SPOT}" opacity="0.8"/>',
             f'<ellipse cx="{cx + 52 * s:.0f}" cy="{cy - 136 * s:.0f}" rx="{22 * s:.0f}" ry="{16 * s:.0f}" fill="{R_SPOT}" opacity="0.8"/>',
             # muzzle
             f'<ellipse cx="{cx}" cy="{cy + 150 * s:.0f}" rx="{140 * s:.0f}" ry="{96 * s:.0f}" fill="{R_MUZZLE}"/>',
             f'<ellipse cx="{cx - 46 * s:.0f}" cy="{cy + 128 * s:.0f}" rx="{14 * s:.0f}" ry="{10 * s:.0f}" fill="{R_SPOT}"/>',
             f'<ellipse cx="{cx + 46 * s:.0f}" cy="{cy + 128 * s:.0f}" rx="{14 * s:.0f}" ry="{10 * s:.0f}" fill="{R_SPOT}"/>',
             f'<path d="M{p(-56, 178)} Q{p(0, 222)} {p(56, 178)}" stroke="{R_SPOT}" stroke-width="{12 * s:.0f}" stroke-linecap="round" fill="none"/>',
             ]
    if eyes == 'wink':
        parts.append(eye(cx - 72 * s, cy - 40 * s, 46 * s, look=(4 * s, 2 * s)))
        parts.append(eye(cx + 72 * s, cy - 40 * s, 46 * s, closed=True, closed_color=PUPIL))
    else:
        parts.append(eye(cx - 72 * s, cy - 40 * s, 46 * s, look=(4 * s, 2 * s)))
        parts.append(eye(cx + 72 * s, cy - 40 * s, 46 * s, look=(-4 * s, 2 * s)))
    # lashes
    for ex, d in ((-72, -1), (72, 1)):
        x0 = cx + ex * s + d * 34 * s
        parts.append(f'<path d="M{x0:.0f} {cy - 76 * s:.0f} l{d * 18 * s:.0f} {-16 * s:.0f}" stroke="{PUPIL}" '
                     f'stroke-width="{8 * s:.0f}" stroke-linecap="round"/>')
    parts.append('</g>')
    return '\n  '.join(parts)


def raffi_neck(x0, y0, x1, y1, w0, w1, band=True):
    """Neck from (x0, y0) (bottom) to (x1, y1) (under the head), with spots,
    a mane along the back and the light-blue band."""
    parts = [f'<path d="M{x0 - w0 / 2:.0f} {y0:.0f} L{x1 - w1 / 2:.0f} {y1:.0f} L{x1 + w1 / 2:.0f} {y1:.0f} '
             f'L{x0 + w0 / 2:.0f} {y0:.0f} Z" fill="{R_COAT}"/>',
             f'<path d="M{x0 - w0 / 2 - 4:.0f} {y0:.0f} L{x1 - w1 / 2 - 4:.0f} {y1:.0f}" stroke="{R_MANE}" '
             f'stroke-width="18" stroke-linecap="round"/>']
    for i, (u, dx, r) in enumerate(((0.2, -0.18, 30), (0.42, 0.16, 26), (0.62, -0.1, 24), (0.82, 0.14, 20))):
        x = x0 + (x1 - x0) * u
        y = y0 + (y1 - y0) * u
        w = w0 + (w1 - w0) * u
        parts.append(f'<ellipse cx="{x + dx * w:.0f}" cy="{y:.0f}" rx="{r * 1.2:.0f}" ry="{r:.0f}" fill="{R_SPOT}" opacity="0.85"/>')
    if band:
        u = 0.3
        x = x0 + (x1 - x0) * u
        y = y0 + (y1 - y0) * u
        w = w0 + (w1 - w0) * u
        parts.append(f'<rect x="{x - w / 2 - 6:.0f}" y="{y - 22:.0f}" width="{w + 12:.0f}" height="44" rx="14" fill="{ACCENT}"/>')
        parts.append(f'<rect x="{x - w / 2 + 8:.0f}" y="{y - 10:.0f}" width="{w - 16:.0f}" height="8" rx="4" fill="{WHITE}" opacity="0.6"/>')
    return '\n  '.join(parts)


def raffi_portrait():
    body = [green_tile(),
            raffi_neck(512, 1000, 512, 600, 260, 210),
            raffi_head(512, 430, 0.95)]
    return svg('RAFFI — portrait (Healthy Body host, the giraffe)', '\n  '.join(body))


def raffi_cheer():
    legs = []
    for x in (360, 430, 600, 670):
        legs.append(f'<rect x="{x - 18}" y="760" width="36" height="150" rx="16" fill="{R_COAT}"/>')
        legs.append(f'<rect x="{x - 20}" y="896" width="40" height="28" rx="10" fill="{R_HOOF}"/>')
    body = [green_tile(),
            '<ellipse cx="512" cy="928" rx="260" ry="20" fill="#1F6B42" opacity="0.5"/>',
            '\n  '.join(legs),
            f'<path d="M700 690 Q770 720 760 790" stroke="{R_COAT}" stroke-width="16" stroke-linecap="round" fill="none"/>',
            f'<ellipse cx="764" cy="800" rx="16" ry="24" fill="{R_MANE}"/>',
            raffi_neck(400, 720, 360, 380, 130, 104),
            f'<ellipse cx="515" cy="720" rx="210" ry="110" fill="{R_COAT}"/>',
            f'<ellipse cx="440" cy="700" rx="40" ry="28" fill="{R_SPOT}" opacity="0.85"/>',
            f'<ellipse cx="560" cy="740" rx="46" ry="30" fill="{R_SPOT}" opacity="0.85"/>',
            f'<ellipse cx="640" cy="690" rx="30" ry="22" fill="{R_SPOT}" opacity="0.85"/>',
            raffi_head(360, 300, 0.58, tilt=-14, eyes='wink')]
    return svg('RAFFI — cheer (standing tall, a wink, the neck tilted)', '\n  '.join(body))


if __name__ == '__main__':
    out = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).resolve().parents[2] / 'assets' / 'hosts')
    out.mkdir(parents=True, exist_ok=True)
    for name, fn in (('luna_portrait', luna_portrait), ('luna_cheer', luna_cheer),
                     ('raffi_portrait', raffi_portrait), ('raffi_cheer', raffi_cheer)):
        (out / f'{name}.svg').write_text(fn())
