"""The course hosts: Luna the owl (Evening Stretch), Raffi the giraffe
(Healthy Body), Aurora the lark (Morning Routine) and Miso the cat (Yoga), drawn in Goro's flat style (rounded tile, soft glow, no
outlines, big eyes with highlights, the light-blue accent of Goro's headband).

    python3 tools/characters/gen_hosts.py [OUT_DIR]

For each host, like Goro: six faces ``<host>_face_<mood>.svg`` (Home; the
happy one also on the course cards), ``<host>_idle.svg`` (Profile) and
``<host>_cheer.svg`` (the workout summary), into OUT_DIR (default:
assets/hosts). Moods as Goro's: happy, sad, angry (the streak at risk; a
calm host looks stern and worried rather than furious), sleeping, excited,
supportive. Edit this script, not the SVG files.
"""

MOODS = ('happy', 'sad', 'angry', 'sleeping', 'excited', 'supportive')
import sys
from pathlib import Path

ACCENT = '#A8D8FF'          # Goro's headband
ACCENT_D = '#7FBFF5'
WHITE = '#FFFFFF'
PUPIL = '#1E1C36'


def tile(grad_id, top, bottom, glow):
    return f'''<defs>
    <linearGradient id="{grad_id}" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:{top}"/>
      <stop offset="100%" style="stop-color:{bottom}"/>
    </linearGradient>
    <radialGradient id="{grad_id}Glow" cx="50%" cy="48%" r="46%">
      <stop offset="0%" style="stop-color:{glow};stop-opacity:0.28"/>
      <stop offset="100%" style="stop-color:{glow};stop-opacity:0"/>
    </radialGradient>
  </defs>
  <rect width="1024" height="1024" rx="224" fill="url(#{grad_id})"/>
  <circle cx="512" cy="500" r="430" fill="url(#{grad_id}Glow)"/>'''


def svg(title, body):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">\n'
            f'  <!-- {title}. Generated by tools/characters/gen_hosts.py: edit the script, not this file. -->\n'
            f'  {body}\n</svg>\n')


def eye(cx, cy, r, look=(0, 0), lid=0.0, lid_color='#000', closed=False, closed_color=PUPIL):
    """A round eye; ``lid`` (0..1) lowers an upper lid of ``lid_color``;
    ``closed`` draws a happy closed eye (an arc) instead."""
    if closed:
        return (f'<path d="M{cx - r * 0.8:.0f} {cy + r * 0.1:.0f} Q{cx:.0f} {cy - r * 0.75:.0f} '
                f'{cx + r * 0.8:.0f} {cy + r * 0.1:.0f}" stroke="{closed_color}" stroke-width="{r * 0.22:.0f}" '
                f'stroke-linecap="round" fill="none"/>')
    px, py = cx + look[0], cy + look[1]
    out = (f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{WHITE}"/>'
           f'<circle cx="{px}" cy="{py}" r="{r * 0.55:.0f}" fill="{PUPIL}"/>'
           f'<circle cx="{px + r * 0.22:.0f}" cy="{py - r * 0.24:.0f}" r="{r * 0.17:.0f}" fill="{WHITE}"/>')
    if lid > 0:
        # a relaxed lid: its edge sags in the middle (a flat edge looks bored)
        y = cy - r + 2 * r * lid
        out += (f'<path d="M{cx - r - 2} {cy - r - 4} L{cx + r + 2} {cy - r - 4} L{cx + r + 2} {y - r * 0.3:.0f} '
                f'Q{cx} {y + r * 0.45:.0f} {cx - r - 2} {y - r * 0.3:.0f} Z" fill="{lid_color}"/>')
    return out


def sleep_eye(cx, cy, r, color):
    """A closed sleeping eye: a downward arc."""
    return (f'<path d="M{cx - r * 0.8:.0f} {cy - r * 0.05:.0f} Q{cx:.0f} {cy + r * 0.6:.0f} '
            f'{cx + r * 0.8:.0f} {cy - r * 0.05:.0f}" stroke="{color}" stroke-width="{r * 0.2:.0f}" '
            f'stroke-linecap="round" fill="none"/>')


def brow(x0, y0, x1, y1, color, width):
    return (f'<path d="M{x0:.0f} {y0:.0f} L{x1:.0f} {y1:.0f}" stroke="{color}" '
            f'stroke-width="{width:.0f}" stroke-linecap="round"/>')


def tear(cx, cy, s):
    return (f'<path d="M{cx:.0f} {cy - 26 * s:.0f} Q{cx + 22 * s:.0f} {cy + 6 * s:.0f} {cx:.0f} {cy + 18 * s:.0f} '
            f'Q{cx - 22 * s:.0f} {cy + 6 * s:.0f} {cx:.0f} {cy - 26 * s:.0f} Z" fill="#8FD0FF"/>')


def zzz(x, y, s, color='#FFFFFF'):
    out = []
    for i, k in enumerate((1.0, 0.75, 0.55)):
        zx, zy, w = x + i * 54 * s, y - i * 62 * s, 44 * s * k
        out.append(f'<path d="M{zx:.0f} {zy:.0f} l{w:.0f} 0 l{-w:.0f} {w:.0f} l{w:.0f} 0" stroke="{color}" '
                   f'stroke-width="{11 * s * k:.0f}" stroke-linecap="round" stroke-linejoin="round" fill="none" opacity="0.9"/>')
    return '\n  '.join(out)


def sparkle(x, y, r, color='#FFE27A'):
    return (f'<path d="M{x} {y - r} L{x + r * 0.25:.0f} {y - r * 0.25:.0f} L{x + r} {y} L{x + r * 0.25:.0f} {y + r * 0.25:.0f} '
            f'L{x} {y + r} L{x - r * 0.25:.0f} {y + r * 0.25:.0f} L{x - r} {y} L{x - r * 0.25:.0f} {y - r * 0.25:.0f} Z" fill="{color}"/>')


def heart(x, y, r, color='#FF7A9C'):
    return (f'<path d="M{x} {y + r * 0.9:.0f} C{x - r * 1.4:.0f} {y - r * 0.1:.0f} {x - r * 0.7:.0f} {y - r * 1.1:.0f} '
            f'{x} {y - r * 0.35:.0f} C{x + r * 0.7:.0f} {y - r * 1.1:.0f} {x + r * 1.4:.0f} {y - r * 0.1:.0f} {x} {y + r * 0.9:.0f} Z" '
            f'fill="{color}"/>')


# ══ Luna, the owl ════════════════════════════════════════════════════════════

L_BODY = '#6E6AAE'      # feathers
L_DARK = '#545090'      # wings, tufts
L_BELLY = '#D8D1F2'
L_MARK = '#B7ADE2'
L_DISC = '#EBE6FA'      # facial disc
L_BEAK = '#F2B544'
L_FEET = '#E9A13B'


def night_sky():
    stars = [(190, 230, 10), (262, 160, 6), (800, 300, 7), (868, 420, 5), (150, 420, 6),
             (330, 260, 4), (720, 180, 5), (880, 640, 6), (140, 700, 5)]
    out = [tile('lunaBg', '#3D428F', '#1D2052', '#8F95E8')]
    out.append('<path d="M780 110 A110 110 0 1 0 880 260 A86 86 0 1 1 780 110 Z" fill="#FFE9A8"/>')
    for x, y, r in stars:
        out.append(f'<circle cx="{x}" cy="{y}" r="{r}" fill="#FFF6D6" opacity="0.85"/>')
    return '\n  '.join(out)


def luna_head(cx, cy, s=1.0, mood='happy'):
    """Head of the owl centred at (cx, cy) in one of the ``MOODS`` (plus
    'joy': eyes closed in a smile, for the cheer pose)."""
    def p(x, y):
        return f'{cx + x * s:.0f} {cy + y * s:.0f}'
    droop = mood in ('sad', 'sleeping')
    tl = (-215, -250) if droop else (-205, -290)       # tuft tips
    tr = (215, -250) if droop else (205, -290)
    parts = [
        f'<path d="M{p(-150, -150)} L{p(*tl)} L{p(-70, -205)} Z" fill="{L_DARK}"/>',
        f'<path d="M{p(150, -150)} L{p(*tr)} L{p(70, -205)} Z" fill="{L_DARK}"/>',
        f'<ellipse cx="{cx}" cy="{cy}" rx="{235 * s:.0f}" ry="{215 * s:.0f}" fill="{L_BODY}"/>',
        f'<ellipse cx="{cx - 88 * s:.0f}" cy="{cy + 6 * s:.0f}" rx="{108 * s:.0f}" ry="{118 * s:.0f}" fill="{L_DISC}"/>',
        f'<ellipse cx="{cx + 88 * s:.0f}" cy="{cy + 6 * s:.0f}" rx="{108 * s:.0f}" ry="{118 * s:.0f}" fill="{L_DISC}"/>',
        f'<path d="M{p(-60, -112)} Q{p(0, -60)} {p(60, -112)} L{p(0, -30)} Z" fill="{L_BODY}"/>',
    ]
    ex, ey, er = 88 * s, cy + 6 * s, 62 * s
    if mood in ('joy', 'supportive'):
        parts.append(eye(cx - ex, ey - 2 * s, er, closed=True, closed_color=L_DARK))
        parts.append(eye(cx + ex, ey - 2 * s, er, closed=True, closed_color=L_DARK))
    elif mood == 'sleeping':
        parts.append(sleep_eye(cx - ex, ey, er, L_DARK))
        parts.append(sleep_eye(cx + ex, ey, er, L_DARK))
    elif mood == 'sad':
        parts.append(eye(cx - ex, ey, er, look=(4 * s, 16 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-4 * s, 16 * s)))
    elif mood == 'angry':
        parts.append(eye(cx - ex, ey, er * 0.92, look=(8 * s, 2 * s)))
        parts.append(eye(cx + ex, ey, er * 0.92, look=(-8 * s, 2 * s)))
    elif mood == 'excited':
        parts.append(eye(cx - ex, ey, er * 1.12, look=(4 * s, 0)))
        parts.append(eye(cx + ex, ey, er * 1.12, look=(-4 * s, 0)))
    else:
        parts.append(eye(cx - ex, ey, er, look=(6 * s, 6 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-6 * s, 6 * s)))
    # feather brows
    bw = 16 * s
    if mood == 'sad':
        parts += [brow(cx - 150 * s, cy - 66 * s, cx - 40 * s, cy - 96 * s, L_DARK, bw),
                  brow(cx + 150 * s, cy - 66 * s, cx + 40 * s, cy - 96 * s, L_DARK, bw)]
    elif mood == 'angry':
        parts += [brow(cx - 150 * s, cy - 96 * s, cx - 44 * s, cy - 70 * s, L_DARK, bw),
                  brow(cx + 150 * s, cy - 96 * s, cx + 44 * s, cy - 70 * s, L_DARK, bw)]
    parts.append(f'<path d="M{p(-26, 70)} L{p(26, 70)} L{p(0, 122)} Z" fill="{L_BEAK}"/>')
    if mood != 'angry':
        parts += [f'<ellipse cx="{cx - 150 * s:.0f}" cy="{cy + 96 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="#F5A8C8" opacity="0.45"/>',
                  f'<ellipse cx="{cx + 150 * s:.0f}" cy="{cy + 96 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="#F5A8C8" opacity="0.45"/>']
    if mood == 'sad':
        parts.append(tear(cx + ex + 30 * s, ey + 86 * s, s))
    if mood == 'sleeping':
        parts.append(zzz(cx + 190 * s, cy - 150 * s, s))
    if mood == 'excited':
        parts += [sparkle(int(cx - 270 * s), int(cy - 180 * s), int(34 * s)),
                  sparkle(int(cx + 280 * s), int(cy - 120 * s), int(28 * s)),
                  sparkle(int(cx + 230 * s), int(cy - 260 * s), int(20 * s))]
    return '\n  '.join(parts)


def luna_body(cx, top, s=1.0, wing='down'):
    """Body below the head: egg shape, belly with V-marks, wings (``wing``
    down: folded | up: the right one raised in a stretch | both: both raised |
    heart: the right one across the chest), a scarf."""
    h = 380 * s
    w = 250 * s
    parts = [
        f'<ellipse cx="{cx}" cy="{top + h * 0.5:.0f}" rx="{w:.0f}" ry="{h * 0.56:.0f}" fill="{L_BODY}"/>',
        f'<ellipse cx="{cx}" cy="{top + h * 0.58:.0f}" rx="{w * 0.66:.0f}" ry="{h * 0.44:.0f}" fill="{L_BELLY}"/>',
    ]
    for row in range(3):
        y = top + h * (0.36 + row * 0.17)
        for col in range(-2 + row % 2, 3, 2):
            x = cx + col * 44 * s
            if abs(col) * 44 * s > w * 0.5:
                continue
            parts.append(f'<path d="M{x - 16 * s:.0f} {y:.0f} L{x:.0f} {y + 16 * s:.0f} L{x + 16 * s:.0f} {y:.0f}" '
                         f'stroke="{L_MARK}" stroke-width="{8 * s:.0f}" stroke-linecap="round" stroke-linejoin="round" fill="none"/>')
    if wing == 'both':
        for sx in (-1, 1):
            parts.append(f'<path d="M{cx + sx * w * 0.7:.0f} {top + h * 0.3:.0f} Q{cx + sx * w * 1.45:.0f} {top + h * 0.05:.0f} '
                         f'{cx + sx * w * 1.25:.0f} {top - h * 0.38:.0f} Q{cx + sx * w * 1.05:.0f} {top + h * 0.02:.0f} '
                         f'{cx + sx * w * 0.62:.0f} {top + h * 0.12:.0f} Z" fill="{L_DARK}"/>')
    else:
        # left wing, folded
        parts.append(f'<path d="M{cx - w * 0.82:.0f} {top + h * 0.22:.0f} Q{cx - w * 1.18:.0f} {top + h * 0.62:.0f} '
                     f'{cx - w * 0.74:.0f} {top + h * 0.98:.0f} Q{cx - w * 0.56:.0f} {top + h * 0.6:.0f} '
                     f'{cx - w * 0.82:.0f} {top + h * 0.22:.0f} Z" fill="{L_DARK}"/>')
    if wing == 'both':
        pass
    elif wing == 'heart':
        parts.append(f'<path d="M{cx + w * 0.8:.0f} {top + h * 0.24:.0f} Q{cx + w * 0.3:.0f} {top + h * 0.34:.0f} '
                     f'{cx - w * 0.05:.0f} {top + h * 0.62:.0f} Q{cx + w * 0.4:.0f} {top + h * 0.7:.0f} '
                     f'{cx + w * 0.78:.0f} {top + h * 0.5:.0f} Z" fill="{L_DARK}"/>')
        parts.append(heart(int(cx - w * 0.02), int(top + h * 0.5), int(30 * s)))
    elif wing == 'up':
        # right wing stretched up and out
        parts.append(f'<path d="M{cx + w * 0.7:.0f} {top + h * 0.3:.0f} Q{cx + w * 1.5:.0f} {top - h * 0.2:.0f} '
                     f'{cx + w * 1.32:.0f} {top - h * 0.58:.0f} Q{cx + w * 1.12:.0f} {top - h * 0.1:.0f} '
                     f'{cx + w * 0.62:.0f} {top + h * 0.12:.0f} Z" fill="{L_DARK}"/>')
        for i in range(3):
            fx = cx + w * (1.3 - i * 0.1)
            fy = top - h * (0.52 - i * 0.1)
            parts.append(f'<ellipse cx="{fx:.0f}" cy="{fy:.0f}" rx="{22 * s:.0f}" ry="{40 * s:.0f}" '
                         f'fill="{L_DARK}" transform="rotate({-30 + i * 12} {fx:.0f} {fy:.0f})"/>')
    else:
        parts.append(f'<path d="M{cx + w * 0.82:.0f} {top + h * 0.22:.0f} Q{cx + w * 1.18:.0f} {top + h * 0.62:.0f} '
                     f'{cx + w * 0.74:.0f} {top + h * 0.98:.0f} Q{cx + w * 0.56:.0f} {top + h * 0.6:.0f} '
                     f'{cx + w * 0.82:.0f} {top + h * 0.22:.0f} Z" fill="{L_DARK}"/>')
    # scarf in Goro's headband blue
    parts.append(f'<path d="M{cx - w * 0.78:.0f} {top + h * 0.08:.0f} Q{cx:.0f} {top + h * 0.22:.0f} '
                 f'{cx + w * 0.78:.0f} {top + h * 0.08:.0f} L{cx + w * 0.74:.0f} {top + h * 0.2:.0f} '
                 f'Q{cx:.0f} {top + h * 0.34:.0f} {cx - w * 0.74:.0f} {top + h * 0.2:.0f} Z" fill="{ACCENT}"/>')
    parts.append(f'<path d="M{cx + w * 0.34:.0f} {top + h * 0.22:.0f} L{cx + w * 0.52:.0f} {top + h * 0.52:.0f} '
                 f'L{cx + w * 0.3:.0f} {top + h * 0.5:.0f} Z" fill="{ACCENT_D}"/>')
    return '\n  '.join(parts)


def luna_feet(cx, y, s=1.0):
    out = []
    for dx in (-70, 70):
        for t in (-22, 0, 22):
            out.append(f'<ellipse cx="{cx + (dx + t) * s:.0f}" cy="{y:.0f}" rx="{13 * s:.0f}" ry="{26 * s:.0f}" fill="{L_FEET}"/>')
    return '\n  '.join(out)


def luna_face(mood):
    wing = {'excited': 'both', 'supportive': 'heart'}.get(mood, 'down')
    body = [night_sky(), luna_body(512, 690, 1.05, wing=wing), luna_head(512, 520, 1.0, mood)]
    return svg(f'LUNA — {mood} (Evening Stretch host, the owl)', '\n  '.join(body))


def luna_idle():
    body = [night_sky(),
            '<rect x="120" y="880" width="784" height="34" rx="17" fill="#2A2D66"/>',
            luna_feet(512, 872, 0.9),
            luna_body(512, 520, 0.9),
            luna_head(512, 380, 0.82, 'happy')]
    return svg('LUNA — idle (standing calmly)', '\n  '.join(body))


def luna_cheer():
    body = [night_sky(),
            '<rect x="120" y="880" width="784" height="34" rx="17" fill="#2A2D66"/>',
            luna_feet(512, 872, 0.9),
            luna_body(512, 520, 0.9, wing='up'),
            luna_head(512, 380, 0.82, 'joy')]
    return svg('LUNA — cheer (stretching a wing, eyes closed happily)', '\n  '.join(body))


# ══ Raffi, the giraffe ═══════════════════════════════════════════════════════

R_COAT = '#F2C462'
R_SPOT = '#C9782F'
R_MUZZLE = '#FBE6B8'
R_EAR_IN = '#E3A04A'
R_HORN = '#E2A452'
R_HORN_TIP = '#6E4321'
R_MANE = '#B8642A'
R_HOOF = '#5A3A22'


def green_tile():
    return tile('raffiBg', '#5DC28C', '#2B8556', '#C8F5D8')


def raffi_head(cx, cy, s=1.0, tilt=0.0, mood='happy'):
    """Head of the giraffe in one of the ``MOODS`` (plus 'wink' for the cheer
    pose); the ears droop when sad or asleep and lie back when stern."""
    def p(x, y):
        return f'{cx + x * s:.0f} {cy + y * s:.0f}'
    ear = {'sad': 48, 'sleeping': 52, 'angry': 4, 'excited': 14}.get(mood, 24)
    parts = [f'<g transform="rotate({tilt} {cx} {cy})">',
             f'<rect x="{cx - 92 * s:.0f}" y="{cy - 270 * s:.0f}" width="{34 * s:.0f}" height="{120 * s:.0f}" rx="{16 * s:.0f}" fill="{R_HORN}"/>',
             f'<rect x="{cx + 58 * s:.0f}" y="{cy - 270 * s:.0f}" width="{34 * s:.0f}" height="{120 * s:.0f}" rx="{16 * s:.0f}" fill="{R_HORN}"/>',
             f'<circle cx="{cx - 75 * s:.0f}" cy="{cy - 272 * s:.0f}" r="{30 * s:.0f}" fill="{R_HORN_TIP}"/>',
             f'<circle cx="{cx + 75 * s:.0f}" cy="{cy - 272 * s:.0f}" r="{30 * s:.0f}" fill="{R_HORN_TIP}"/>']
    for sx in (-1, 1):
        ex_, ey_ = cx + sx * 200 * s, cy - 130 * s
        parts.append(f'<ellipse cx="{ex_:.0f}" cy="{ey_:.0f}" rx="{84 * s:.0f}" ry="{34 * s:.0f}" fill="{R_COAT}" '
                     f'transform="rotate({sx * ear} {cx + sx * 150 * s:.0f} {ey_:.0f})"/>')
        parts.append(f'<ellipse cx="{ex_ - sx * 4 * s:.0f}" cy="{ey_ + 2 * s:.0f}" rx="{56 * s:.0f}" ry="{18 * s:.0f}" fill="{R_EAR_IN}" '
                     f'transform="rotate({sx * ear} {cx + sx * 150 * s:.0f} {ey_:.0f})"/>')
    parts += [
        f'<path d="M{p(-150, -110)} C{p(-160, -230)} {p(160, -230)} {p(150, -110)} '
        f'C{p(160, 20)} {p(140, 150)} {p(110, 200)} L{p(-110, 200)} C{p(-140, 150)} {p(-160, 20)} {p(-150, -110)} Z" fill="{R_COAT}"/>',
        f'<ellipse cx="{cx - 40 * s:.0f}" cy="{cy - 150 * s:.0f}" rx="{30 * s:.0f}" ry="{20 * s:.0f}" fill="{R_SPOT}" opacity="0.8"/>',
        f'<ellipse cx="{cx + 52 * s:.0f}" cy="{cy - 136 * s:.0f}" rx="{22 * s:.0f}" ry="{16 * s:.0f}" fill="{R_SPOT}" opacity="0.8"/>',
        f'<ellipse cx="{cx}" cy="{cy + 150 * s:.0f}" rx="{140 * s:.0f}" ry="{96 * s:.0f}" fill="{R_MUZZLE}"/>',
        f'<ellipse cx="{cx - 46 * s:.0f}" cy="{cy + 122 * s:.0f}" rx="{14 * s:.0f}" ry="{10 * s:.0f}" fill="{R_SPOT}"/>',
        f'<ellipse cx="{cx + 46 * s:.0f}" cy="{cy + 122 * s:.0f}" rx="{14 * s:.0f}" ry="{10 * s:.0f}" fill="{R_SPOT}"/>',
    ]
    # mouth
    if mood == 'sad':
        parts.append(f'<path d="M{p(-46, 196)} Q{p(0, 166)} {p(46, 196)}" stroke="{R_SPOT}" stroke-width="{12 * s:.0f}" stroke-linecap="round" fill="none"/>')
    elif mood == 'angry':
        parts.append(f'<path d="M{p(-44, 186)} L{p(44, 186)}" stroke="{R_SPOT}" stroke-width="{12 * s:.0f}" stroke-linecap="round"/>')
    elif mood == 'sleeping':
        parts.append(f'<ellipse cx="{cx}" cy="{cy + 188 * s:.0f}" rx="{16 * s:.0f}" ry="{12 * s:.0f}" fill="{R_SPOT}"/>')
    elif mood == 'excited':
        parts.append(f'<path d="M{p(-66, 168)} Q{p(0, 176)} {p(66, 168)} Q{p(56, 236)} {p(0, 236)} Q{p(-56, 236)} {p(-66, 168)} Z" fill="#8A3F1E"/>')
        parts.append(f'<ellipse cx="{cx}" cy="{cy + 218 * s:.0f}" rx="{30 * s:.0f}" ry="{14 * s:.0f}" fill="#F08A8A"/>')
    else:
        parts.append(f'<path d="M{p(-56, 172)} Q{p(0, 216)} {p(56, 172)}" stroke="{R_SPOT}" stroke-width="{12 * s:.0f}" stroke-linecap="round" fill="none"/>')
    # eyes
    ex, ey, er = 72 * s, cy - 40 * s, 46 * s
    if mood == 'wink':
        parts.append(eye(cx - ex, ey, er, look=(4 * s, 2 * s)))
        parts.append(eye(cx + ex, ey, er, closed=True, closed_color=PUPIL))
    elif mood == 'supportive':
        parts.append(eye(cx - ex, ey, er, closed=True, closed_color=PUPIL))
        parts.append(eye(cx + ex, ey, er, closed=True, closed_color=PUPIL))
    elif mood == 'sleeping':
        parts.append(sleep_eye(cx - ex, ey, er, PUPIL))
        parts.append(sleep_eye(cx + ex, ey, er, PUPIL))
    elif mood == 'sad':
        parts.append(eye(cx - ex, ey, er, look=(2 * s, 12 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-2 * s, 12 * s)))
    elif mood == 'excited':
        parts.append(eye(cx - ex, ey, er * 1.12, look=(3 * s, 0)))
        parts.append(eye(cx + ex, ey, er * 1.12, look=(-3 * s, 0)))
    else:
        parts.append(eye(cx - ex, ey, er, look=(4 * s, 2 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-4 * s, 2 * s)))
    # brows (sad, stern) or lashes
    if mood == 'sad':
        parts += [brow(cx - 110 * s, cy - 92 * s, cx - 40 * s, cy - 112 * s, R_MANE, 12 * s),
                  brow(cx + 110 * s, cy - 92 * s, cx + 40 * s, cy - 112 * s, R_MANE, 12 * s)]
    elif mood == 'angry':
        parts += [brow(cx - 112 * s, cy - 112 * s, cx - 38 * s, cy - 92 * s, R_MANE, 12 * s),
                  brow(cx + 112 * s, cy - 112 * s, cx + 38 * s, cy - 92 * s, R_MANE, 12 * s)]
    else:
        for exs, d in ((-72, -1), (72, 1)):
            x0 = cx + exs * s + d * 34 * s
            parts.append(f'<path d="M{x0:.0f} {cy - 76 * s:.0f} l{d * 18 * s:.0f} {-16 * s:.0f}" stroke="{PUPIL}" '
                         f'stroke-width="{8 * s:.0f}" stroke-linecap="round"/>')
    if mood == 'sad':
        parts.append(tear(cx + ex + 24 * s, ey + 70 * s, s * 0.9))
    parts.append('</g>')
    if mood == 'sleeping':
        parts.append(zzz(cx + 170 * s, cy - 210 * s, s))
    if mood == 'excited':
        parts += [sparkle(int(cx - 250 * s), int(cy - 250 * s), int(30 * s)),
                  sparkle(int(cx + 260 * s), int(cy - 40 * s), int(26 * s)),
                  sparkle(int(cx - 270 * s), int(cy + 40 * s), int(20 * s))]
    if mood == 'supportive':
        parts.append(heart(int(cx + 210 * s), int(cy + 110 * s), int(34 * s)))
    return '\n  '.join(parts)


def raffi_neck(x0, y0, x1, y1, w0, w1, band=True):
    """Neck from (x0, y0) (bottom) to (x1, y1) (under the head), with spots,
    a mane along the back and the light-blue band."""
    parts = [f'<path d="M{x0 - w0 / 2:.0f} {y0:.0f} L{x1 - w1 / 2:.0f} {y1:.0f} L{x1 + w1 / 2:.0f} {y1:.0f} '
             f'L{x0 + w0 / 2:.0f} {y0:.0f} Z" fill="{R_COAT}"/>',
             f'<path d="M{x0 - w0 / 2 - 4:.0f} {y0:.0f} L{x1 - w1 / 2 - 4:.0f} {y1:.0f}" stroke="{R_MANE}" '
             f'stroke-width="18" stroke-linecap="round"/>']
    for i, (u, dx, r) in enumerate(((0.2, -0.18, 30), (0.42, 0.16, 26), (0.62, -0.1, 24), (0.82, 0.14, 20))):
        x = x0 + (x1 - x0) * u
        y = y0 + (y1 - y0) * u
        w = w0 + (w1 - w0) * u
        parts.append(f'<ellipse cx="{x + dx * w:.0f}" cy="{y:.0f}" rx="{r * 1.2:.0f}" ry="{r:.0f}" fill="{R_SPOT}" opacity="0.85"/>')
    if band:
        u = 0.3
        x = x0 + (x1 - x0) * u
        y = y0 + (y1 - y0) * u
        w = w0 + (w1 - w0) * u
        parts.append(f'<rect x="{x - w / 2 - 6:.0f}" y="{y - 22:.0f}" width="{w + 12:.0f}" height="44" rx="14" fill="{ACCENT}"/>')
        parts.append(f'<rect x="{x - w / 2 + 8:.0f}" y="{y - 10:.0f}" width="{w - 16:.0f}" height="8" rx="4" fill="{WHITE}" opacity="0.6"/>')
    return '\n  '.join(parts)


def raffi_face(mood):
    body = [green_tile(),
            raffi_neck(512, 1000, 512, 600, 260, 210),
            raffi_head(512, 430, 0.95, mood=mood)]
    return svg(f'RAFFI — {mood} (Healthy Body host, the giraffe)', '\n  '.join(body))


def raffi_standing(tilt, mood, title):
    legs = []
    for x in (360, 430, 600, 670):
        legs.append(f'<rect x="{x - 18}" y="760" width="36" height="150" rx="16" fill="{R_COAT}"/>')
        legs.append(f'<rect x="{x - 20}" y="896" width="40" height="28" rx="10" fill="{R_HOOF}"/>')
    body = [green_tile(),
            '<ellipse cx="512" cy="928" rx="260" ry="20" fill="#1F6B42" opacity="0.5"/>',
            '\n  '.join(legs),
            f'<path d="M700 690 Q770 720 760 790" stroke="{R_COAT}" stroke-width="16" stroke-linecap="round" fill="none"/>',
            f'<ellipse cx="764" cy="800" rx="16" ry="24" fill="{R_MANE}"/>',
            raffi_neck(400, 720, 360, 380, 130, 104),
            f'<ellipse cx="515" cy="720" rx="210" ry="110" fill="{R_COAT}"/>',
            f'<ellipse cx="440" cy="700" rx="40" ry="28" fill="{R_SPOT}" opacity="0.85"/>',
            f'<ellipse cx="560" cy="740" rx="46" ry="30" fill="{R_SPOT}" opacity="0.85"/>',
            f'<ellipse cx="640" cy="690" rx="30" ry="22" fill="{R_SPOT}" opacity="0.85"/>',
            raffi_head(360, 300, 0.58, tilt=tilt, mood=mood)]
    return svg(title, '\n  '.join(body))


def raffi_idle():
    return raffi_standing(0, 'happy', 'RAFFI — idle (standing calmly)')


def raffi_cheer():
    return raffi_standing(-14, 'wink', 'RAFFI — cheer (standing tall, a wink, the neck tilted)')


# ══ Aurora, the lark ═════════════════════════════════════════════════════════

A_BODY = '#C8935E'      # warm sandy brown
A_DARK = '#9A6A40'      # wings, crest, streaks
A_BELLY = '#F7E6C8'
A_FACE = '#F3DDB8'      # pale face patch round the eyes
A_STREAK = '#B98452'
A_BEAK = '#F0A53A'
A_BEAK_D = '#C97E22'
A_FEET = '#E8957A'
A_CHEEK = '#FF9C8A'


def sunrise():
    out = [tile('auroraBg', '#FFD49A', '#F58E6E', '#FFF3C4')]
    out.append('<circle cx="512" cy="1010" r="300" fill="#FFE9A0" opacity="0.55"/>')
    out.append('<circle cx="512" cy="1010" r="220" fill="#FFF2C2" opacity="0.7"/>')
    for x, y, r in ((170, 250, 34), (238, 232, 26), (846, 560, 30), (892, 544, 22)):
        out.append(f'<circle cx="{x}" cy="{y}" r="{r}" fill="#FFFFFF" opacity="0.55"/>')
    return '\n  '.join(out)


def note(x, y, s, color='#FFFFFF'):
    """A musical note (the lark sings at dawn)."""
    return (f'<g opacity="0.92"><ellipse cx="{x:.0f}" cy="{y:.0f}" rx="{20 * s:.0f}" ry="{15 * s:.0f}" fill="{color}" '
            f'transform="rotate(-20 {x:.0f} {y:.0f})"/>'
            f'<rect x="{x + 13 * s:.0f}" y="{y - 70 * s:.0f}" width="{8 * s:.0f}" height="{72 * s:.0f}" rx="{4 * s:.0f}" fill="{color}"/>'
            f'<path d="M{x + 17 * s:.0f} {y - 70 * s:.0f} q{30 * s:.0f} {10 * s:.0f} {30 * s:.0f} {40 * s:.0f}" stroke="{color}" '
            f'stroke-width="{8 * s:.0f}" stroke-linecap="round" fill="none"/></g>')


def aurora_head(cx, cy, s=1.0, mood='happy'):
    """Head of the lark in one of the ``MOODS`` (plus 'joy': eyes closed,
    singing, for the cheer pose). The crest perks up when excited and lies
    flat when sad or asleep; the beak opens to sing."""
    def p(x, y):
        return f'{cx + x * s:.0f} {cy + y * s:.0f}'
    lift = {'sad': -0.55, 'sleeping': -0.7, 'angry': -0.2, 'excited': 0.35, 'joy': 0.3}.get(mood, 0.0)
    parts = []
    # crest: three feathers fanning back from the crown
    for ang, ln in ((-30, 190), (-8, 230), (14, 170)):
        a = ang - 40 * lift
        parts.append(f'<ellipse cx="{cx:.0f}" cy="{cy - (180 + ln * 0.45) * s:.0f}" rx="{26 * s:.0f}" ry="{ln * 0.5 * s:.0f}" '
                     f'fill="{A_DARK}" transform="rotate({a:.0f} {cx:.0f} {cy - 170 * s:.0f})"/>')
    parts += [
        f'<ellipse cx="{cx}" cy="{cy}" rx="{215 * s:.0f}" ry="{200 * s:.0f}" fill="{A_BODY}"/>',
        f'<ellipse cx="{cx}" cy="{cy + 128 * s:.0f}" rx="{150 * s:.0f}" ry="{70 * s:.0f}" fill="{A_FACE}"/>',
        f'<circle cx="{cx - 82 * s:.0f}" cy="{cy + 20 * s:.0f}" r="{68 * s:.0f}" fill="{A_FACE}" opacity="0.55"/>',
        f'<circle cx="{cx + 82 * s:.0f}" cy="{cy + 20 * s:.0f}" r="{68 * s:.0f}" fill="{A_FACE}" opacity="0.55"/>',
    ]
    # Goro's headband, under the crest
    parts += [f'<path d="M{p(-205, -96)} Q{p(0, -168)} {p(205, -96)} L{p(200, -46)} Q{p(0, -118)} {p(-200, -46)} Z" fill="{ACCENT}"/>',
              f'<path d="M{p(-150, -100)} Q{p(0, -150)} {p(150, -100)}" stroke="{WHITE}" stroke-width="{9 * s:.0f}" '
              f'stroke-linecap="round" fill="none" opacity="0.6"/>']
    ex, ey, er = 82 * s, cy + 20 * s, 58 * s
    if mood in ('joy', 'supportive'):
        parts.append(eye(cx - ex, ey, er, closed=True, closed_color=A_DARK))
        parts.append(eye(cx + ex, ey, er, closed=True, closed_color=A_DARK))
    elif mood == 'sleeping':
        parts.append(sleep_eye(cx - ex, ey, er, A_DARK))
        parts.append(sleep_eye(cx + ex, ey, er, A_DARK))
    elif mood == 'sad':
        parts.append(eye(cx - ex, ey, er, look=(4 * s, 15 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-4 * s, 15 * s)))
    elif mood == 'angry':
        parts.append(eye(cx - ex, ey, er * 0.92, look=(8 * s, 2 * s)))
        parts.append(eye(cx + ex, ey, er * 0.92, look=(-8 * s, 2 * s)))
    elif mood == 'excited':
        parts.append(eye(cx - ex, ey, er * 1.12, look=(4 * s, 0)))
        parts.append(eye(cx + ex, ey, er * 1.12, look=(-4 * s, 0)))
    else:
        parts.append(eye(cx - ex, ey, er, look=(6 * s, 6 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-6 * s, 6 * s)))
    bw = 15 * s
    if mood == 'sad':
        parts += [brow(cx - 140 * s, cy - 20 * s, cx - 44 * s, cy - 46 * s, A_DARK, bw),
                  brow(cx + 140 * s, cy - 20 * s, cx + 44 * s, cy - 46 * s, A_DARK, bw)]
    elif mood == 'angry':
        parts += [brow(cx - 140 * s, cy - 50 * s, cx - 48 * s, cy - 24 * s, A_DARK, bw),
                  brow(cx + 140 * s, cy - 50 * s, cx + 48 * s, cy - 24 * s, A_DARK, bw)]
    # beak: closed, or open to sing
    if mood in ('excited', 'joy'):
        parts += [f'<path d="M{p(-34, 92)} L{p(34, 92)} L{p(0, 128)} Z" fill="{A_BEAK}"/>',
                  f'<path d="M{p(-26, 140)} L{p(26, 140)} L{p(0, 170)} Z" fill="{A_BEAK_D}"/>',
                  f'<ellipse cx="{cx}" cy="{cy + 132 * s:.0f}" rx="{18 * s:.0f}" ry="{9 * s:.0f}" fill="#8A3F1E"/>']
    else:
        parts += [f'<path d="M{p(-28, 90)} L{p(28, 90)} L{p(0, 166)} Z" fill="{A_BEAK}"/>',
                  f'<path d="M{p(0, 90)} L{p(28, 90)} L{p(0, 166)} Z" fill="{A_BEAK_D}" opacity="0.35"/>']
    if mood != 'angry':
        parts += [f'<ellipse cx="{cx - 150 * s:.0f}" cy="{cy + 112 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="{A_CHEEK}" opacity="0.5"/>',
                  f'<ellipse cx="{cx + 150 * s:.0f}" cy="{cy + 112 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="{A_CHEEK}" opacity="0.5"/>']
    if mood == 'sad':
        parts.append(tear(cx + ex + 30 * s, ey + 84 * s, s))
    if mood == 'sleeping':
        parts.append(zzz(cx + 190 * s, cy - 140 * s, s))
    if mood == 'excited':
        parts += [note(cx - 300 * s, cy - 110 * s, s), note(cx + 270 * s, cy - 170 * s, 0.85 * s),
                  sparkle(int(cx + 300 * s), int(cy + 20 * s), int(24 * s), '#FFFFFF')]
    return '\n  '.join(parts)


def aurora_body(cx, top, s=1.0, wing='down'):
    """Body below the head: a round body with a streaked cream breast, wings
    (``wing`` down: folded | up: the right one waving | both: both raised |
    heart: the right one across the chest) and a short tail."""
    h = 360 * s
    w = 240 * s
    parts = [
        f'<path d="M{cx - w * 0.3:.0f} {top + h * 0.9:.0f} L{cx - w * 0.62:.0f} {top + h * 1.12:.0f} '
        f'L{cx - w * 0.12:.0f} {top + h * 0.98:.0f} Z" fill="{A_DARK}"/>',
        f'<path d="M{cx + w * 0.3:.0f} {top + h * 0.9:.0f} L{cx + w * 0.62:.0f} {top + h * 1.12:.0f} '
        f'L{cx + w * 0.12:.0f} {top + h * 0.98:.0f} Z" fill="{A_DARK}"/>',
        f'<ellipse cx="{cx}" cy="{top + h * 0.5:.0f}" rx="{w * 0.9:.0f}" ry="{h * 0.56:.0f}" fill="{A_BODY}"/>',
        f'<ellipse cx="{cx}" cy="{top + h * 0.6:.0f}" rx="{w * 0.56:.0f}" ry="{h * 0.42:.0f}" fill="{A_BELLY}"/>',
    ]
    for row in range(3):
        y = top + h * (0.34 + row * 0.15)
        for col in range(-2 + row % 2, 3, 2):
            x = cx + col * 38 * s
            if abs(col) * 38 * s > w * 0.4:
                continue
            parts.append(f'<path d="M{x:.0f} {y - 14 * s:.0f} Q{x + 10 * s:.0f} {y + 6 * s:.0f} {x:.0f} {y + 14 * s:.0f} '
                         f'Q{x - 10 * s:.0f} {y + 6 * s:.0f} {x:.0f} {y - 14 * s:.0f} Z" fill="{A_STREAK}" opacity="0.85"/>')

    def folded(sx):
        return (f'<path d="M{cx + sx * w * 0.72:.0f} {top + h * 0.2:.0f} Q{cx + sx * w * 1.08:.0f} {top + h * 0.6:.0f} '
                f'{cx + sx * w * 0.66:.0f} {top + h * 0.98:.0f} Q{cx + sx * w * 0.48:.0f} {top + h * 0.58:.0f} '
                f'{cx + sx * w * 0.72:.0f} {top + h * 0.2:.0f} Z" fill="{A_DARK}"/>')

    def raised(sx):
        out = [f'<path d="M{cx + sx * w * 0.7:.0f} {top + h * 0.3:.0f} Q{cx + sx * w * 1.5:.0f} {top - h * 0.1:.0f} '
               f'{cx + sx * w * 1.3:.0f} {top - h * 0.5:.0f} Q{cx + sx * w * 1.08:.0f} {top - h * 0.04:.0f} '
               f'{cx + sx * w * 0.62:.0f} {top + h * 0.12:.0f} Z" fill="{A_DARK}"/>']
        for i in range(3):
            fx = cx + sx * w * (1.28 - i * 0.1)
            fy = top - h * (0.46 - i * 0.1)
            out.append(f'<ellipse cx="{fx:.0f}" cy="{fy:.0f}" rx="{20 * s:.0f}" ry="{38 * s:.0f}" '
                       f'fill="{A_DARK}" transform="rotate({sx * (30 - i * 12)} {fx:.0f} {fy:.0f})"/>')
        return '\n  '.join(out)

    if wing == 'both':
        parts += [raised(-1), raised(1)]
    else:
        parts.append(folded(-1))
        if wing == 'up':
            parts.append(raised(1))
        elif wing == 'heart':
            parts.append(f'<path d="M{cx + w * 0.8:.0f} {top + h * 0.22:.0f} Q{cx + w * 0.3:.0f} {top + h * 0.32:.0f} '
                         f'{cx - w * 0.05:.0f} {top + h * 0.6:.0f} Q{cx + w * 0.4:.0f} {top + h * 0.68:.0f} '
                         f'{cx + w * 0.78:.0f} {top + h * 0.48:.0f} Z" fill="{A_DARK}"/>')
            parts.append(heart(int(cx - w * 0.02), int(top + h * 0.48), int(30 * s)))
        else:
            parts.append(folded(1))
    return '\n  '.join(parts)


def aurora_feet(cx, y, s=1.0):
    out = []
    for dx in (-60, 60):
        out.append(f'<rect x="{cx + (dx - 7) * s:.0f}" y="{y - 70 * s:.0f}" width="{14 * s:.0f}" height="{66 * s:.0f}" rx="{7 * s:.0f}" fill="{A_FEET}"/>')
        for t in (-26, 0, 26):
            out.append(f'<ellipse cx="{cx + (dx + t) * s:.0f}" cy="{y:.0f}" rx="{20 * s:.0f}" ry="{9 * s:.0f}" fill="{A_FEET}"/>')
    return '\n  '.join(out)


def aurora_face(mood):
    wing = {'excited': 'both', 'supportive': 'heart'}.get(mood, 'down')
    body = [sunrise(), aurora_body(512, 700, 1.05, wing=wing), aurora_head(512, 500, 1.0, mood)]
    return svg(f'AURORA — {mood} (Morning Routine host, the lark)', '\n  '.join(body))


def aurora_standing(wing, mood, title):
    body = [sunrise(),
            '<rect x="120" y="880" width="784" height="34" rx="17" fill="#D9705A" opacity="0.7"/>',
            aurora_feet(512, 872, 0.9),
            aurora_body(512, 500, 0.9, wing=wing),
            aurora_head(512, 360, 0.8, mood)]
    return svg(title, '\n  '.join(body))


def aurora_idle():
    return aurora_standing('down', 'happy', 'AURORA — idle (standing calmly)')


def aurora_cheer():
    svg_text = aurora_standing('up', 'joy', 'AURORA — cheer (waving a wing, singing)')
    notes = '\n  '.join([note(250, 300, 1.0), note(790, 220, 0.8)])
    return svg_text.replace('\n</svg>', f'\n  {notes}\n</svg>')


# ══ Miso, the cat ════════════════════════════════════════════════════════════

M_FUR = '#F0A35E'       # ginger
M_STRIPE = '#D77F3B'
M_CREAM = '#FCE6C8'     # muzzle, chest, paws
M_EAR_IN = '#F7AEB9'
M_NOSE = '#EE8A9E'
M_MOUTH = '#8A4B2A'
M_WHISKER = '#FFF6EA'
M_BELL = '#F5C842'
M_FUR_BACK = '#E2914C'   # a raised leg behind the head, a shade darker


def calm_teal():
    out = [tile('misoBg', '#62CFC0', '#1E7F86', '#DFFFF8')]
    out.append('<circle cx="512" cy="470" r="360" fill="#FFFFFF" opacity="0.12"/>')
    for x, y, r in ((176, 236, 14), (232, 176, 9), (846, 300, 12), (884, 372, 7), (150, 640, 9), (878, 700, 11)):
        out.append(f'<circle cx="{x}" cy="{y}" r="{r}" fill="#FFFFFF" opacity="0.5"/>')
    return '\n  '.join(out)


def miso_head(cx, cy, s=1.0, mood='happy'):
    """Head of the cat in one of the ``MOODS`` (plus 'joy': eyes closed, a
    happy open mouth, for the cheer pose). The ears droop when sad or asleep,
    flatten sideways when stern and perk up when excited."""
    def p(x, y):
        return f'{cx + x * s:.0f} {cy + y * s:.0f}'
    ear = {'sad': -34, 'sleeping': -18, 'angry': -48, 'excited': 6, 'joy': 4}.get(mood, 0)
    parts = []
    for sx in (-1, 1):
        base = (cx + sx * 132 * s, cy - 150 * s)
        rot_ = f'transform="rotate({sx * -ear} {base[0]:.0f} {base[1]:.0f})"'
        parts.append(f'<path d="M{p(sx * 214, -96)} L{p(sx * 186, -318)} L{p(sx * 40, -182)} Z" fill="{M_FUR}" '
                     f'stroke="{M_FUR}" stroke-width="{36 * s:.0f}" stroke-linejoin="round" {rot_}/>')
        parts.append(f'<path d="M{p(sx * 176, -132)} L{p(sx * 168, -262)} L{p(sx * 86, -176)} Z" fill="{M_EAR_IN}" '
                     f'stroke="{M_EAR_IN}" stroke-width="{16 * s:.0f}" stroke-linejoin="round" {rot_}/>')
    parts += [
        # cheek fluff under the wide head
        f'<path d="M{p(-232, 30)} L{p(-262, 96)} L{p(-196, 84)} L{p(-214, 136)} L{p(-150, 120)} Z" fill="{M_FUR}"/>',
        f'<path d="M{p(232, 30)} L{p(262, 96)} L{p(196, 84)} L{p(214, 136)} L{p(150, 120)} Z" fill="{M_FUR}"/>',
        f'<ellipse cx="{cx}" cy="{cy}" rx="{238 * s:.0f}" ry="{196 * s:.0f}" fill="{M_FUR}"/>',
    ]
    # tabby marks on the forehead and the cheeks
    for dx, h in ((-46, 64), (0, 84), (46, 64)):
        parts.append(f'<rect x="{cx + (dx - 11) * s:.0f}" y="{cy - 192 * s:.0f}" width="{22 * s:.0f}" height="{h * s:.0f}" '
                     f'rx="{11 * s:.0f}" fill="{M_STRIPE}"/>')
    for sx in (-1, 1):
        for i, y in enumerate((20, 56)):
            parts.append(f'<path d="M{p(sx * 238, y)} L{p(sx * (176 + 14 * i), y + 8)}" stroke="{M_STRIPE}" '
                         f'stroke-width="{16 * s:.0f}" stroke-linecap="round"/>')
    # muzzle: two cream lobes and a chin
    parts += [f'<ellipse cx="{cx}" cy="{cy + 150 * s:.0f}" rx="{58 * s:.0f}" ry="{34 * s:.0f}" fill="{M_CREAM}"/>',
              f'<circle cx="{cx - 52 * s:.0f}" cy="{cy + 104 * s:.0f}" r="{64 * s:.0f}" fill="{M_CREAM}"/>',
              f'<circle cx="{cx + 52 * s:.0f}" cy="{cy + 104 * s:.0f}" r="{64 * s:.0f}" fill="{M_CREAM}"/>']
    ex, ey, er = 92 * s, cy - 6 * s, 60 * s
    if mood in ('joy', 'supportive'):
        parts.append(eye(cx - ex, ey, er, closed=True, closed_color=M_MOUTH))
        parts.append(eye(cx + ex, ey, er, closed=True, closed_color=M_MOUTH))
    elif mood == 'sleeping':
        parts.append(sleep_eye(cx - ex, ey, er, M_MOUTH))
        parts.append(sleep_eye(cx + ex, ey, er, M_MOUTH))
    elif mood == 'sad':
        parts.append(eye(cx - ex, ey, er, look=(4 * s, 16 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-4 * s, 16 * s)))
    elif mood == 'angry':
        parts.append(eye(cx - ex, ey, er * 0.92, look=(8 * s, 2 * s)))
        parts.append(eye(cx + ex, ey, er * 0.92, look=(-8 * s, 2 * s)))
    elif mood == 'excited':
        parts.append(eye(cx - ex, ey, er * 1.12, look=(4 * s, 0)))
        parts.append(eye(cx + ex, ey, er * 1.12, look=(-4 * s, 0)))
    else:
        parts.append(eye(cx - ex, ey, er, look=(6 * s, 6 * s)))
        parts.append(eye(cx + ex, ey, er, look=(-6 * s, 6 * s)))
    bw = 15 * s
    if mood == 'sad':
        parts += [brow(cx - 150 * s, cy - 54 * s, cx - 52 * s, cy - 84 * s, M_STRIPE, bw),
                  brow(cx + 150 * s, cy - 54 * s, cx + 52 * s, cy - 84 * s, M_STRIPE, bw)]
    elif mood == 'angry':
        parts += [brow(cx - 150 * s, cy - 86 * s, cx - 54 * s, cy - 60 * s, M_STRIPE, bw),
                  brow(cx + 150 * s, cy - 86 * s, cx + 54 * s, cy - 60 * s, M_STRIPE, bw)]
    # nose and mouth
    parts.append(f'<path d="M{p(-26, 62)} L{p(26, 62)} L{p(0, 92)} Z" fill="{M_NOSE}" stroke="{M_NOSE}" '
                 f'stroke-width="{12 * s:.0f}" stroke-linejoin="round"/>')
    mw = 9 * s
    if mood in ('excited', 'joy'):
        parts += [f'<path d="M{p(-46, 112)} Q{p(0, 104)} {p(46, 112)} Q{p(36, 176)} {p(0, 176)} Q{p(-36, 176)} {p(-46, 112)} Z" fill="{M_MOUTH}"/>',
                  f'<ellipse cx="{cx}" cy="{cy + 160 * s:.0f}" rx="{22 * s:.0f}" ry="{12 * s:.0f}" fill="#F08A8A"/>']
    elif mood == 'sad':
        parts.append(f'<path d="M{p(-36, 140)} Q{p(0, 112)} {p(36, 140)}" stroke="{M_MOUTH}" stroke-width="{mw:.0f}" '
                     f'stroke-linecap="round" fill="none"/>')
    elif mood == 'angry':
        parts.append(f'<path d="M{p(-34, 128)} L{p(34, 128)}" stroke="{M_MOUTH}" stroke-width="{mw:.0f}" stroke-linecap="round"/>')
    else:
        parts.append(f'<path d="M{p(0, 92)} L{p(0, 110)} M{p(-44, 112)} Q{p(-22, 136)} {p(0, 110)} Q{p(22, 136)} {p(44, 112)}" '
                     f'stroke="{M_MOUTH}" stroke-width="{mw:.0f}" stroke-linecap="round" stroke-linejoin="round" fill="none"/>')
    # whiskers
    for sx in (-1, 1):
        for y0, y1 in ((96, 70), (116, 118), (136, 164)):
            parts.append(f'<path d="M{p(sx * 120, y0)} L{p(sx * 286, y1)}" stroke="{M_WHISKER}" stroke-width="{7 * s:.0f}" '
                         f'stroke-linecap="round" opacity="0.9"/>')
    if mood not in ('angry',):
        parts += [f'<ellipse cx="{cx - 168 * s:.0f}" cy="{cy + 84 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="{M_EAR_IN}" opacity="0.55"/>',
                  f'<ellipse cx="{cx + 168 * s:.0f}" cy="{cy + 84 * s:.0f}" rx="{30 * s:.0f}" ry="{16 * s:.0f}" fill="{M_EAR_IN}" opacity="0.55"/>']
    if mood == 'sad':
        parts.append(tear(cx + ex + 34 * s, ey + 82 * s, s))
    if mood == 'sleeping':
        parts.append(zzz(cx + 200 * s, cy - 170 * s, s))
    if mood == 'excited':
        parts += [sparkle(int(cx - 290 * s), int(cy - 180 * s), int(34 * s)),
                  sparkle(int(cx + 300 * s), int(cy - 110 * s), int(28 * s)),
                  sparkle(int(cx + 250 * s), int(cy - 270 * s), int(20 * s))]
    return '\n  '.join(parts)


def miso_paw(x, y, s, angle=0.0):
    """A front paw: a cream oval with three toe marks."""
    out = [f'<g transform="rotate({angle:.0f} {x:.0f} {y:.0f})">',
           f'<ellipse cx="{x:.0f}" cy="{y:.0f}" rx="{46 * s:.0f}" ry="{36 * s:.0f}" fill="{M_CREAM}"/>']
    for dx in (-18, 0, 18):
        out.append(f'<path d="M{x + dx * s:.0f} {y - 30 * s:.0f} L{x + dx * s:.0f} {y - 14 * s:.0f}" stroke="{M_STRIPE}" '
                   f'stroke-width="{5 * s:.0f}" stroke-linecap="round" opacity="0.6"/>')
    out.append('</g>')
    return '\n  '.join(out)


def miso_arm(sx, x0, y0, x1, y1, s):
    """A front leg from the shoulder (x0, y0) to the paw (x1, y1)."""
    return (f'<path d="M{x0:.0f} {y0:.0f} L{x1:.0f} {y1:.0f}" stroke="{M_FUR}" stroke-width="{70 * s:.0f}" '
            f'stroke-linecap="round"/>')


def miso_body(cx, top, s=1.0, paws='down', lotus=False):
    """Body below the head: a round sitting body with a cream chest, the
    collar (Goro's headband blue) with a bell, a tail curled round, and front
    paws (``paws`` down: resting in front | knees: on the knees of the lotus |
    up: both raised over the head, palms together | both: both raised in a V |
    heart: one over the chest holding a heart). ``lotus`` adds crossed legs."""
    h = 360 * s
    w = 250 * s
    parts = [
        # tail, behind the body, curling up on the right
        f'<path d="M{cx + w * 0.6:.0f} {top + h * 0.95:.0f} Q{cx + w * 1.45:.0f} {top + h * 0.9:.0f} '
        f'{cx + w * 1.3:.0f} {top + h * 0.35:.0f} Q{cx + w * 1.22:.0f} {top + h * 0.12:.0f} {cx + w * 1.05:.0f} {top + h * 0.2:.0f}" '
        f'stroke="{M_FUR}" stroke-width="{58 * s:.0f}" stroke-linecap="round" fill="none"/>',
        f'<path d="M{cx + w * 1.32:.0f} {top + h * 0.42:.0f} L{cx + w * 1.18:.0f} {top + h * 0.44:.0f} '
        f'M{cx + w * 1.38:.0f} {top + h * 0.66:.0f} L{cx + w * 1.22:.0f} {top + h * 0.62:.0f}" '
        f'stroke="{M_STRIPE}" stroke-width="{16 * s:.0f}" stroke-linecap="round"/>',
        f'<ellipse cx="{cx}" cy="{top + h * 0.55:.0f}" rx="{w * 0.86:.0f}" ry="{h * 0.56:.0f}" fill="{M_FUR}"/>',
        f'<ellipse cx="{cx}" cy="{top + h * 0.56:.0f}" rx="{w * 0.5:.0f}" ry="{h * 0.42:.0f}" fill="{M_CREAM}"/>',
    ]
    for sx in (-1, 1):
        parts.append(f'<path d="M{cx + sx * w * 0.86:.0f} {top + h * 0.5:.0f} L{cx + sx * w * 0.62:.0f} {top + h * 0.54:.0f} '
                     f'M{cx + sx * w * 0.84:.0f} {top + h * 0.72:.0f} L{cx + sx * w * 0.64:.0f} {top + h * 0.74:.0f}" '
                     f'stroke="{M_STRIPE}" stroke-width="{16 * s:.0f}" stroke-linecap="round"/>')
    if lotus:
        # crossed hind legs: the thighs out to the sides, the feet crossed in front
        for sx in (-1, 1):
            parts.append(f'<ellipse cx="{cx + sx * w * 0.62:.0f}" cy="{top + h * 1.02:.0f}" rx="{w * 0.6:.0f}" ry="{h * 0.15:.0f}" '
                         f'fill="{M_FUR}" transform="rotate({sx * 6} {cx + sx * w * 0.62:.0f} {top + h * 1.02:.0f})"/>')
        parts += [f'<ellipse cx="{cx - w * 0.2:.0f}" cy="{top + h * 1.08:.0f}" rx="{w * 0.22:.0f}" ry="{h * 0.08:.0f}" fill="{M_CREAM}"/>',
                  f'<ellipse cx="{cx + w * 0.2:.0f}" cy="{top + h * 1.04:.0f}" rx="{w * 0.22:.0f}" ry="{h * 0.08:.0f}" fill="{M_CREAM}"/>']
    sh_y = top + h * 0.22
    if paws == 'both':
        for sx in (-1, 1):
            x0 = cx + sx * w * 0.62
            x1, y1 = cx + sx * w * 1.25, top - h * 0.62
            parts.append(miso_arm(sx, x0, sh_y, x1, y1, s))
            parts.append(miso_paw(x1, y1, s * 0.9, sx * 30))
    elif paws == 'heart':
        parts.append(miso_arm(-1, cx - w * 0.6, sh_y, cx - w * 0.42, top + h * 0.98, s))
        parts.append(miso_paw(cx - w * 0.42, top + h * 0.98, s))
        parts.append(miso_arm(1, cx + w * 0.6, sh_y, cx + w * 0.08, top + h * 0.5, s))
        parts.append(heart(int(cx - w * 0.06), int(top + h * 0.5), int(36 * s)))
        parts.append(miso_paw(cx + w * 0.14, top + h * 0.52, s * 0.9, -30))
    elif paws == 'knees':
        for sx in (-1, 1):
            parts.append(miso_arm(sx, cx + sx * w * 0.6, sh_y, cx + sx * w * 0.86, top + h * 0.9, s))
            parts.append(miso_paw(cx + sx * w * 0.9, top + h * 0.92, s * 0.9))
    else:
        for sx in (-1, 1):
            parts.append(miso_arm(sx, cx + sx * w * 0.5, sh_y, cx + sx * w * 0.36, top + h * 0.98, s))
            parts.append(miso_paw(cx + sx * w * 0.36, top + h * 0.98, s))
    # collar with a bell
    parts += [f'<path d="M{cx - w * 0.66:.0f} {top + h * 0.06:.0f} Q{cx:.0f} {top + h * 0.2:.0f} {cx + w * 0.66:.0f} {top + h * 0.06:.0f} '
              f'L{cx + w * 0.62:.0f} {top + h * 0.17:.0f} Q{cx:.0f} {top + h * 0.31:.0f} {cx - w * 0.62:.0f} {top + h * 0.17:.0f} Z" fill="{ACCENT}"/>',
              f'<circle cx="{cx}" cy="{top + h * 0.3:.0f}" r="{26 * s:.0f}" fill="{M_BELL}"/>',
              f'<path d="M{cx - 14 * s:.0f} {top + h * 0.31:.0f} L{cx + 14 * s:.0f} {top + h * 0.31:.0f}" stroke="#B88A1E" '
              f'stroke-width="{6 * s:.0f}" stroke-linecap="round"/>']
    return '\n  '.join(parts)


def miso_face(mood):
    paws = {'excited': 'both', 'supportive': 'heart'}.get(mood, 'down')
    body = [calm_teal(), miso_body(512, 700, 1.05, paws=paws), miso_head(512, 500, 1.0, mood)]
    return svg(f'MISO — {mood} (Yoga host, the cat)', '\n  '.join(body))


def miso_mat():
    return (f'<rect x="132" y="872" width="760" height="42" rx="21" fill="{ACCENT}"/>'
            f'<rect x="172" y="884" width="680" height="8" rx="4" fill="{WHITE}" opacity="0.55"/>')


def miso_idle():
    body = [calm_teal(), miso_mat(), miso_body(512, 470, 0.9, paws='knees', lotus=True),
            miso_head(512, 330, 0.8, 'happy')]
    return svg('MISO — idle (sitting in lotus, paws on the knees)', '\n  '.join(body))


def miso_arms_overhead(cx, sh_y, head_cy, hs, bs):
    """Both front legs raised overhead, elbows out wide round the head (``hs``
    its scale); drawn behind the head, which covers their inner part."""
    w = 250 * bs
    out = []
    for sx in (-1, 1):
        x0 = cx + sx * w * 0.62
        ctrl = (cx + sx * 470 * hs, head_cy - 250 * hs)
        end = (cx + sx * 24 * hs, head_cy - 360 * hs)
        out.append(f'<path d="M{x0:.0f} {sh_y:.0f} Q{ctrl[0]:.0f} {ctrl[1]:.0f} {end[0]:.0f} {end[1]:.0f}" '
                   f'stroke="{M_FUR}" stroke-width="{66 * bs:.0f}" stroke-linecap="round" fill="none"/>')
    return '\n  '.join(out)


def miso_cheer():
    hs, bs, head_cy, top = 0.68, 0.8, 420, 556
    sh_y = top + 360 * bs * 0.22
    tip_y = head_cy - 372 * hs
    body = [calm_teal(), miso_mat(), miso_arms_overhead(512, sh_y, head_cy, hs, bs),
            miso_body(512, top, bs, paws='up', lotus=True),
            miso_head(512, head_cy, hs, 'joy'),
            miso_paw(512 - 22 * hs, tip_y, bs * 0.9, -90), miso_paw(512 + 22 * hs, tip_y, bs * 0.9, 90),
            sparkle(200, 330, 30), sparkle(836, 300, 24), sparkle(800, 560, 18)]
    return svg('MISO — cheer (lotus, paws together over the head, eyes closed happily)', '\n  '.join(body))


def all_art():
    out = {}
    for mood in MOODS:
        out[f'luna_face_{mood}'] = luna_face(mood)
        out[f'raffi_face_{mood}'] = raffi_face(mood)
        out[f'aurora_face_{mood}'] = aurora_face(mood)
        out[f'miso_face_{mood}'] = miso_face(mood)
    out.update(luna_idle=luna_idle(), luna_cheer=luna_cheer(),
               raffi_idle=raffi_idle(), raffi_cheer=raffi_cheer(),
               aurora_idle=aurora_idle(), aurora_cheer=aurora_cheer(),
               miso_idle=miso_idle(), miso_cheer=miso_cheer())
    return out


if __name__ == '__main__':
    out = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).resolve().parents[2] / 'assets' / 'hosts')
    out.mkdir(parents=True, exist_ok=True)
    for name, text in all_art().items():
        (out / f'{name}.svg').write_text(text)
