// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:caliday/data/models/custom_routine.dart';
import 'package:caliday/data/models/enums.dart';
import 'package:caliday/data/models/exercise_result.dart';
import 'package:caliday/data/models/friend_profile.dart';
import 'package:caliday/data/models/skill_progress.dart';
import 'package:caliday/data/models/user_profile.dart';
import 'package:caliday/data/models/workout_log.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BranchIdAdapter());
    registerAdapter(CourseIdAdapter());
    registerAdapter(CustomRoutineAdapter());
    registerAdapter(ExerciseResultAdapter());
    registerAdapter(ExerciseTypeAdapter());
    registerAdapter(FitnessGoalAdapter());
    registerAdapter(FriendProfileAdapter());
    registerAdapter(RankAdapter());
    registerAdapter(SetTypeAdapter());
    registerAdapter(SkillProgressAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WorkoutLogAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BranchIdAdapter());
    registerAdapter(CourseIdAdapter());
    registerAdapter(CustomRoutineAdapter());
    registerAdapter(ExerciseResultAdapter());
    registerAdapter(ExerciseTypeAdapter());
    registerAdapter(FitnessGoalAdapter());
    registerAdapter(FriendProfileAdapter());
    registerAdapter(RankAdapter());
    registerAdapter(SetTypeAdapter());
    registerAdapter(SkillProgressAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WorkoutLogAdapter());
  }
}
